import { manifestHash } from "./manifest";
import { collectResources } from "./publish";
import type {
    GeneticsManifest,
    ManifestPage,
    PublishState,
} from "../shared/types";

function resourceId(
    key: string,
    state: PublishState,
    expectedHashes: Map<string, string>
): string {
    const resource = state.resources[key];
    const expectedHash = expectedHashes.get(key);
    if (
        !resource ||
        resource.status !== "verified" ||
        !expectedHash ||
        resource.contentHash !== expectedHash
    ) {
        throw new Error(`missing verified resource for ${key}`);
    }
    return resource.id;
}

function pageRequest(
    page: ManifestPage,
    pageIndex: number,
    state: PublishState,
    expectedHashes: Map<string, string>
): unknown {
    const base = {
        pageIndex,
        activeNavbarTitles: page.activeNavbarTitles,
        secondaryTitle: page.secondaryTitle,
    };
    switch (page.type) {
        case "material":
            return {
                ...base,
                request: {
                    type: "material",
                    content: {
                        imageId: resourceId(
                            page.imageKey,
                            state,
                            expectedHashes
                        ),
                        descriptionId: resourceId(
                            page.description.key,
                            state,
                            expectedHashes
                        ),
                    },
                    questionSections: page.questionSections.map((section) => ({
                        titleId: resourceId(
                            section.title.key,
                            state,
                            expectedHashes
                        ),
                        questionId: resourceId(
                            section.question.key,
                            state,
                            expectedHashes
                        ),
                    })),
                },
            };
        case "questions":
            return {
                ...base,
                request: {
                    type: "questions",
                    columns: page.columns.map((column) => ({
                        labelId: resourceId(
                            column.label.key,
                            state,
                            expectedHashes
                        ),
                        questions: column.questions.map((question) => ({
                            titleId: resourceId(
                                question.title.key,
                                state,
                                expectedHashes
                            ),
                            questionId: resourceId(
                                question.question.key,
                                state,
                                expectedHashes
                            ),
                        })),
                    })),
                },
            };
        case "overview":
            return {
                ...base,
                request: {
                    type: "overview",
                    headerId: page.headers.map((header) =>
                        resourceId(header.key, state, expectedHashes)
                    ),
                    contentId: page.rows.map((row) =>
                        row.map((cell) =>
                            resourceId(cell.key, state, expectedHashes)
                        )
                    ),
                },
            };
    }
}

function toTypeScriptLiteral(value: unknown): string {
    return JSON.stringify(value, null, 4).replace(
        /^(\s+)"([A-Za-z_$][\w$]*)":/gm,
        "$1$2:"
    );
}

export function renderCourseResource(
    manifest: GeneticsManifest,
    state: PublishState
): string {
    const currentManifestHash = manifestHash(manifest);
    if (state.manifestHash !== currentManifestHash) {
        throw new Error("publish state does not match the current manifest");
    }
    const resources = collectResources(manifest);
    const expectedHashes = new Map(
        resources.map((resource) => [resource.key, resource.contentHash])
    );
    const courseUnits = manifest.units.map((unit) => ({
        id: unit.id,
        title: unit.title,
        category: unit.category,
        order: unit.order,
        pages: unit.pages.map((page, index) =>
            pageRequest(page, index, state, expectedHashes)
        ),
    }));

    // This file is generated by tools/genetics-importer. Do not edit manually.
    return `import type { CourseUnit } from "../types/types";\n\nexport const courseUnits: CourseUnit[] = ${toTypeScriptLiteral(courseUnits)};\n`;
}
